version: "3.7"
services:
  db:
    restart: always
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - PGDATA:/var/lib/postgresql/data
  redis:
    restart: always
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"
    volumes:
      - /www/static/
    volumes_from:
      - "web"
      # - "frontend"
    depends_on:
      - web
  # frontend:
  #   build: ./unleash-ui-pwa/
  #   volumes:
  #     - /app/dist/
  web-core:
    image: calssiq/unleash:0.1
    expose:
      - "8000"
    command: flask db upgrade
    depends_on:
      - db
    env_file:
      - .env
  web:
    restart: always
    image: calssiq/unleash:0.1
    volumes:
      - .:/code
    expose:
      - "8000"
    command: gunicorn --bind 0.0.0.0:8000 main:app --log-file -
    depends_on:
      - web-core
    ports:
      - "8000:8000"
    env_file:
      - .env
  web-celery:
    restart: always
    volumes:
      - .:/code
    image: calssiq/unleash:0.1
    command: celery -A main.celery_app worker -l INFO -P eventlet
    depends_on:
      - web-core
    env_file:
      - .env
  web-beat:
    volumes:
      - .:/code
    restart: always
    image: calssiq/unleash:0.1
    command: celery -A main.celery_app beat -l INFO
    depends_on:
      - web-core
    env_file:
      - .env
volumes:
  PGDATA:
