version: '2'
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=unleash
    ports:
      - "5432:5432"
    volumes:
      - PGDATA:/var/lib/postgresql/data/pgdat
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"
    volumes:
      - /www/static/
    volumes_from:
      - web
    links:
      - web:web
    depends_on:
      - web
  web:
    restart: always
    build: .
    expose:
      - "8000"
    command: gunicorn --bind 0.0.0.0:8000 main:app --log-file -
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  PGDATA: