version: "3.7"
services:
  db:
    restart: always
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - PGDATA:/var/lib/postgresql/data
  redis:
    restart: always
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
  recommendation-api:
    build:
      context: ./recommendation_api
    ports:
      - "8000:8000"
volumes:
  PGDATA:
    external: true