version: "3.7"
services:
  db:
    restart: always
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - PGDATA:/var/lib/postgresql/data
  redis:
    restart: always
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"
    volumes:
      - /www/static/
    volumes_from:
      - "web"
      - "frontend"
    depends_on:
      - web
  frontend:
    build: ./unleash-ui-pwa/
    volumes:
      - /app/dist/
  web-core:
    image: web-core
    build: .
    expose:
      - "8000"
    command: flask db upgrade
    depends_on:
      - db
  web:
    restart: always
    image: web-core
    volumes:
      - .:/code
    expose:
      - "8000"
    command: gunicorn --bind 0.0.0.0:8000 main:app --log-file -
    depends_on:
      - web-core
    ports:
      - "8000:8000"
  web-celery:
    restart: always
    volumes:
      - .:/code
    image: web-core
    command: celery -A main.celery_app worker -l INFO -P eventlet
    depends_on:
      - web-core
  web-beat:
    volumes:
      - .:/code
    restart: always
    image: web-core
    command: celery -A main.celery_app beat -l INFO
    depends_on:
      - web-core
volumes:
  PGDATA:
