version: '2'
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=unleash
    expose:
      - "5432"
    # ports:
    #   - "5432:5432"
  # redis:
  #   restart: always
  #   image: redis
  #   expose:
  #     - "6379"
  #   ports:
  #     - "6379:6379"
  # nginx:
  #   restart: always
  #   build: ./nginx/
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /www/static/
  #   volumes_from:
  #     - web
  #   links:
  #     - web:web
  #   depends_on:
  #     - web
  web:
    restart: always
    build: .
    # command: gunicorn main:app --bind 0.0.0.0:5000
    command: flask run  --host=0.0.0.0
    volumes:
      - .:/code
    expose:
      - "5000"
    depends_on:
      - db
    # env_file:
    #   - .env
    ports:
      - "80:5000"
