"""add post table

Revision ID: 08c668a53c0f
Revises: a8df99aeb1e7
Create Date: 2021-04-21 08:54:45.707904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c668a53c0f'
down_revision = 'a8df99aeb1e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Unicode(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('post_type', sa.Unicode(length=300), nullable=True),
    sa.Column('template', sa.Unicode(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
