"""add follwing

Revision ID: 947dfa244559
Revises: c9335fde1705
Create Date: 2021-05-06 16:52:21.168821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '947dfa244559'
down_revision = 'c9335fde1705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmark', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('bookmark', 'chapter_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('following', sa.Column('user_following_id', sa.Integer(), nullable=True))
    op.drop_constraint('following_ibfk_4', 'following', type_='foreignkey')
    op.create_foreign_key(None, 'following', 'user', ['user_following_id'], ['id'])
    op.drop_column('following', 'user_following')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('following', sa.Column('user_following', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'following', type_='foreignkey')
    op.create_foreign_key('following_ibfk_4', 'following', 'user', ['user_following'], ['id'])
    op.drop_column('following', 'user_following_id')
    op.alter_column('bookmark', 'chapter_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('bookmark', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
