"""init

Revision ID: 5d740711f3eb
Revises: 6c9871b894e1
Create Date: 2021-05-14 02:07:47.274601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d740711f3eb'
down_revision = '6c9871b894e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('facebook', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('name', sa.Unicode(length=256), nullable=True))
    op.drop_column('user', 'facebook_id')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('facebook_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'name')
    op.drop_column('user', 'facebook')
    # ### end Alembic commands ###
