"""empty message

Revision ID: 662e666daba9
Revises: 730efde4108a
Create Date: 2023-07-02 21:04:13.442168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662e666daba9'
down_revision = '730efde4108a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_mod', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_mod')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
