"""empty message

Revision ID: 730efde4108a
Revises: 5012bd2a7187
Create Date: 2023-07-02 20:48:18.413419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730efde4108a'
down_revision = '5012bd2a7187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.drop_constraint('author_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('author_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
