"""add status column

Revision ID: 75ff51d8fe62
Revises: f78bc7a5ff59
Create Date: 2021-05-06 22:25:47.333886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ff51d8fe62'
down_revision = 'f78bc7a5ff59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiction', sa.Column('status', sa.Unicode(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiction', 'status')
    # ### end Alembic commands ###
