"""update relationship of user and author

Revision ID: a77aca39a9cc
Revises: 08c668a53c0f
Create Date: 2021-04-21 09:58:37.084061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77aca39a9cc'
down_revision = '08c668a53c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'author', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.drop_column('author', 'user_id')
    # ### end Alembic commands ###
