"""add title to media table

Revision ID: a8df99aeb1e7
Revises: c1fd6f69d3cc
Create Date: 2021-04-20 20:47:57.242175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8df99aeb1e7'
down_revision = 'c1fd6f69d3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('title', sa.Unicode(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'title')
    # ### end Alembic commands ###
