"""add short desc

Revision ID: b5321e580048
Revises: 5bbf35f24f0a
Create Date: 2021-05-05 20:03:06.349831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5321e580048'
down_revision = '5bbf35f24f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiction', sa.Column('short_desc', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiction', 'short_desc')
    # ### end Alembic commands ###
