"""add task

Revision ID: d80cc3db4654
Revises: b171ba402b6a
Create Date: 2023-09-06 16:09:48.097238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80cc3db4654'
down_revision = 'b171ba402b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fiction', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fiction'], ['fiction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
